[package]
name = "tufted"
version = "0.1.0"
entrypoint = "tufted.typ"
authors = ["Vsevolod Shegolev <https://github.com/vsheg>", "Yousa-Mirage <https://github.com/Yousa-Mirage>"]
homepage = "https://tsxb.top"
repository = "https://github.com/tsx8/tufted"
license = "MIT"
description = "Responsive web layout with wide margins, elegant sidenotes, and restrained typography."
compiler = "0.14.0"
exclude = ["tests"]
categories = ["layout", "utility"]
keywords = ["website"]
